const moviesData = [
  {
    id: 1,
    title: "Pritam and Pedro",
    year: 2026,
    genre: "cybercrime comedy-thriller and buddy-cop drama",
    rating: IMDb 7.8/10 || TMDB 8.6/10,
    poster: "https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/380/1782998630380-h",
    backdrop: "https://picsum.photos/seed/dune-back/1280/720",
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset.",
    duration: "2h 35m",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
    trailerUrl: "https://mega.nz/file/m7AXWBgI#i8qSF3q9r0xgTiibF1bqp2q5i4BPzpQ77P34UZU_CDk",
    categories: ["trending", "popular", "topRated", "recommended"],
    tags: ["sci-fi", "adventure"]
  },
  {
    id: 2,
    title: "The Batman",
    year: 2022,
    genre: "Action",
    rating: 7.8,
    poster: "https://picsum.photos/seed/batman/300/450",
    backdrop: "https://picsum.photos/seed/batman-back/1280/720",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate.",
    duration: "2h 56m",
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["trending", "popular", "newReleases"],
    tags: ["action", "crime"]
  },
  {
    id: 3,
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.7,
    poster: "https://picsum.photos/seed/interstellar/300/450",
    backdrop: "https://picsum.photos/seed/interstellar-back/1280/720",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    duration: "2h 49m",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["topRated", "popular", "recommended"],
    tags: ["sci-fi", "drama"]
  },
  {
    id: 4,
    title: "Joker",
    year: 2019,
    genre: "Drama",
    rating: 8.4,
    poster: "https://picsum.photos/seed/joker/300/450",
    backdrop: "https://picsum.photos/seed/joker-back/1280/720",
    description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.",
    duration: "2h 2m",
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["popular", "recommended"],
    tags: ["drama", "thriller"]
  },
  {
    id: 5,
    title: "Spider-Man: No Way Home",
    year: 2021,
    genre: "Action",
    rating: 8.3,
    poster: "https://picsum.photos/seed/spiderman/300/450",
    backdrop: "https://picsum.photos/seed/spiderman-back/1280/720",
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help.",
    duration: "2h 28m",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["trending", "newReleases", "popular"],
    tags: ["action", "adventure"]
  },
  {
    id: 6,
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    rating: 8.5,
    poster: "https://picsum.photos/seed/parasite/300/450",
    backdrop: "https://picsum.photos/seed/parasite-back/1280/720",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    duration: "2h 12m",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["topRated", "recommended"],
    tags: ["thriller", "drama"]
  },
  {
    id: 7,
    title: "Tenet",
    year: 2020,
    genre: "Sci-Fi",
    rating: 7.3,
    poster: "https://picsum.photos/seed/tenet/300/450",
    backdrop: "https://picsum.photos/seed/tenet-back/1280/720",
    description: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.",
    duration: "2h 30m",
    director: "Christopher Nolan",
    cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["newReleases", "popular"],
    tags: ["sci-fi", "action"]
  },
  {
    id: 8,
    title: "Avatar: The Way of Water",
    year: 2022,
    genre: "Sci-Fi",
    rating: 7.6,
    poster: "https://picsum.photos/seed/avatar2/300/450",
    backdrop: "https://picsum.photos/seed/avatar2-back/1280/720",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.",
    duration: "3h 12m",
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["trending", "newReleases"],
    tags: ["sci-fi", "adventure"]
  },
  {
    id: 9,
    title: "Oppenheimer",
    year: 2023,
    genre: "Biography",
    rating: 8.9,
    poster: "https://picsum.photos/seed/oppenheimer/300/450",
    backdrop: "https://picsum.photos/seed/oppenheimer-back/1280/720",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    duration: "3h 0m",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["trending", "topRated", "popular"],
    tags: ["biography", "drama"]
  },
  {
    id: 10,
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
    poster: "https://picsum.photos/seed/inception/300/450",
    backdrop: "https://picsum.photos/seed/inception-back/1280/720",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    duration: "2h 28m",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    trailerUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: ["topRated", "popular", "recommended"],
    tags: ["sci-fi", "action"]
  }
];

// Expose globally
window.moviesData = moviesData;